name: Ansible_Deployment

on:
  workflow_dispatch:
     # inputs:
      # environment:
      #   description: 'The environment to deploy to'
      #   required: true
      #   default: 'staging'
  #push:
   # branches:
    #  - main  # Trigger on changes to the main branch

jobs:
  deploy:
    runs-on: ansible-runner # Specify your self-hosted runner's label here
    env:
      working-directory: /home/krishna/actions-runner/git
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Copy Playbook and Inventory to Runner
        working-directory: ${{ env.working-directory}}
        run: |
          cp -r jenkins.yml .
          cp -r inventory.ini .
          cp -r domain_join.sh .
          chmod a+x domain_join.sh

      - name: Copy Playbook and Inventory to Runner
        working-directory: ${{ env.working-directory}}
        run: 
          ./domain_join.sh
          
      - name: Run Ansible Playbook
        working-directory: ${{ env.working-directory}}
        run: |
          ansible-playbook -i playbook/inventory.ini playbook/jenkins.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"  # Disable host key checking
