name: EC2 Instance Created

on:
  workflow_run:
    workflows: ["Trigger Workflow"]
    types:
      - completed

jobs:
  update_inventory:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update Inventory File
      run: |
        # Use the provided EC2 instance IP address and update your inventory.ini file
        echo "[ec2]" > inventory.ini
        echo "instance ansible_host=$INSTANCE_IP" >> inventory.ini

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini jenkins.yml
