name: Terraform Plan & Apply

# on:
#   pull_request:
#     branches-ignore:
#       - main
#     types: [opened, synchronize, reopened]

#   issue_comment:
#     types: [created]

jobs:
  terraform-plan:
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    outputs:
      tf_plan_success: ${{ steps.plan.outputs.success }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: "init"
          tf_actions_working_dir: "terraform"

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: "fmt"
          tf_actions_working_dir: "terraform"

      - name: Terraform Plan
        id: plan
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: "plan"
          tf_actions_working_dir: "terraform"

  terraform-apply:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.comment.body == 'terraform apply --auto-approve' &&
      github.event.issue.pull_request
    needs: terraform-plan
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: "apply --auto-approve"
          tf_actions_working_dir: "terraform"
